<template>
  <div class="players-catalog">
    <div class="players-list">
      <md-list>
        <md-list-item v-for="player in players.content" :key="player.id" md-expand-multiple>
          <md-icon><i class="fa fa-address-card" aria-hidden="true"></i></md-icon>
          <span> {{ player.name }}</span>

          <md-list-expand>
            <ul>
              <li>Name: {{player.name}}</li>
              <li>IP: {{player.ip}}</li>
              <li>Port: {{player.port}}</li>
              <li>Path: {{player.path}}</li>
              <li>Difficulty: {{player.difficulty}}</li>
              <li>Token: {{player.token}}</li>
            </ul>
            <div class="iataaa-panel">
              <md-button class="md-raised md-warn" @click.native="onClickDeletePlayer(player)">
                <i class="fa fa-trash" aria-hidden="true"></i>
                Delete
              </md-button>
              <md-button class="md-raised md-primary" @click.native="onClickEditPlayer(player)">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                Edit
              </md-button>
            </div>
          </md-list-expand>
        </md-list-item>
      </md-list>
    </div>
    <div class="pagination-container">
      <pagination :currentPage="currentPage"
                  :totalPages="totalPages"
                  @onClickPage="onClickPage($event)"
      ></pagination>
    </div>
  </div>
</template>
<script>
  import Pagination from './Pagination'
  export default {
    components: {
      Pagination
    },
    name: 'players-catalog',
    props: ['players'],
    computed: {
      currentPage () {
        return this.players.number
      },
      totalPages () {
        return this.players.totalPages
      }
    },
    methods: {
      onClickDeletePlayer (player) {
        this.$emit('onClickDeletePlayer', player)
      },
      onClickEditPlayer (player) {
        this.$emit('onClickEditPlayer', player)
      },
      onClickPage (pageNb) {
        this.$emit('onClickPage', pageNb)
      }
    }
  }
</script>

<style lang="less" scoped>
  .players-list {
    overflow-y: auto;
    height: 62vh;
  }
  .pagination-container {
    margin-top: 5px;
  }

  .md-list { // Generated by vue material
    padding: 0;
  }
</style>
