spring:
  application:
    name: checkersManager-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_DATABASE}?useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.MySQL5Dialect