ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000

  routes:
    aiplayer-service:
        path: /aiplayer-service/**
        serviceId: aiplayer-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 8080
